bullet-train-co/bullet_train

README.md

Added Discord link to README file to make it easier for folks to discover the community.

Adds Discord link in README

---

bin/configure

Fixes https://github.com/bullet-train-co/bullet_train/issues/40.

Fixing hyphen inputs on `bin/configure`.

---

.overmind.env
bin/dev
bin/setup

Makes Overmind default

---

bin/configure

・Closes #46.
Nothing special, just adding the GitHub setup portion under an `if` statement.
Let me know if this works for you! 👍

Add option to skip GitHub setup

---

bin/theme

・Addresses the TODOs in `bin/theme`
I also added a few things to help the developer navigate, etc.

Check if file exists in `bin/theme`

---

app/javascript/application.js

application.js: include jquery before @rails/ujs

---

test/system/dates_helper_test.rb

Addresses the TODO in `test/system/dates_helper_test.rb`

Add time zone check in dates helper test

---

test/system/webhooks_system_test.rb

Test update for https://github.com/bullet-train-co/bullet_train-outgoing_webhooks/pull/8 to pass CI

Update webhooks_system_test for async processing of webhook generation

---

test/bin/setup-super-scaffolding-system-test
test/system/super_scaffolding_partial_test.rb

I decided to deal with this one separately from the other partial tests because it was a little more involved. The main fixes are in the joint PRs.
Joint PRs
- https://github.com/bullet-train-co/bullet_train-themes-tailwind_css/pull/13
- https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/51

Add multiple options test in partial test

---

app/javascript/controllers/index.js

Add missing sortable Stimulus controller

---

test/controllers/api/v1/scaffolding/completely_concrete/tangible_things_endpoint_test.rb
test/support/custom_assertions.rb

Closes #345 (duplicate of https://github.com/bullet-train-co/bullet-train-tailwind-css/issues/547)
Joint PR
- https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/50

Remove Super Scaffolded Minitest deprecations

---

test/controllers/api/v1/scaffolding/completely_concrete/tangible_things_controller_test.rb

Details in Joint PR
- https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/85

Adjust API controller test for super scaffolding file fields

---

Procfile.dev
bin/setup
esbuild.config.js
package.json

Some notable things:
- Add code splitting
- Allow multiple entrypoints which can share code.
- Remove `build:light` for JS and move it to an environment variable (happy to change the ENV var)

[RFC / WIP]: Rework bundling

---

app/views/account/teams/show.html.erb

The main information for this PR can be found in the `bullet_train-super_scaffolding` joint PR below.
Joint PRs
- https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/83
- https://github.com/bullet-train-co/bullet_train-themes/pull/23
Most of the `CreativeConcept` and `TangibleThing` logic is in `bullet_train-super_scaffolding`, but this is the only one I found needed editing from directly within the starter repository.

Update Teams show page for collection rendering feature

---

README.md

Update README to add running setup script

---

.circleci/config.yml
test/system/application_platform_test.rb
test/system/super_scaffolding_partial_test.rb

Closes #651.
This fixes the application platform test, but I'll still have to work on the partial tests.

Clean up system tests after running Super Scaffolding test setup script

---

esbuild.config.js

Relates to https://github.com/bullet-train-co/bullet_train/issues/622

Fixes esbuild.config.js error

---

app/views/account/teams/show.html.erb

This PR removes the nested `unless` block from `line 11`.  The `unless` from `line 7` should be enough.

Remove uncessary nested unless block

---

config/initializers/theme.rb

Merge after this PR has been merged:
https://github.com/bullet-train-co/bullet_train-core/pull/33

Remove unused `original_devise_path`

---

config/initializers/openai.rb

Closes https://github.com/bullet-train-co/bullet_train-core/issues/212
Joint PR:
- https://github.com/bullet-train-co/bullet_train-core/pull/213

Add OpenAI initializer

---

test/factories/scaffolding/absolutely_abstract/creative_concepts.rb
test/factories/scaffolding/completely_concrete/tangible_things.rb
test/factories/teams.rb
test/factories/users.rb
test/factories/webhooks/outgoing/endpoints.rb

Dependant of https://github.com/bullet-train-co/bullet_train-core/pull/84

Added example factories for use with FactoryBot.example

---

test/system/super_scaffolding_partial_test.rb

fix typo in super_scaffolding_partial_test.rb

---

app.json
bin/configure

Replace application name in `app.json`

---

test/factories/users.rb

Required by https://github.com/bullet-train-co/bullet_train-core/pull/258

Fix: user_example

---

test/controllers/api/open_api_controller_test.rb
test/system/open_api_v3_test.rb

- rewrite as a controller test
Fixes #664

OpenAPI system test is flakey

---

Gemfile.lock
package.json
yarn.lock

Bump CableReady JS package to v5.0

---

test/system/dates_helper_test.rb
test/system/invitations_test.rb
test/system/membership_test.rb

Specify records used in system tests more precisely

---

bin/hack

- https://github.com/bullet-train-co/bullet_train-core/pull/265

Update develop rake task to hack

---

.circleci/config.yml
bin/checkout-and-link-core-repo

This will make it easier to test joint PRs that span both repos.

Add a script to pull a matching branch from the core repo if it exists

---

bin/checkout-and-link-core-repo

This makes it so that the `Core:` tests in CI will run against the JS provided by the gems/packages in `core` instead of running against the JS provided by the published versions on npm.

Try linking yarn in CI

---

test/controllers/api/v1/platform/applications_controller_test.rb

Add platform applications controller test

---

app/helpers/routes_helper.rb
config/routes.rb

Move `collection_actions` into `RoutesHelper`

---

test/system/super_scaffolding_partial_test.rb
test/system/tangible_thing_test.rb

This PR upgrades the test suites in regard to the related changes introduced in bullet_train-co https://github.com/bullet-train-co/bullet_train-core/pull/393

Themes localization - test suite upgrade

---

.github/workflows/version-bump.yml

Need to watch the files we're interested in bumping.

[release process] Use the correct paths for the PR

---

.github/workflows/tag-release.yml

Sorry for the nitpickiness!
I'm a fan of all the GitHub release workflows though 👍

Fix typo in tag release file

---

test/bin/setup-action-models-system-test

Continues https://github.com/bullet-train-co/bullet_train/pull/706

More changes of `sidebar` to `navbar`

---

test/system/action_models_test.rb

Another bit from https://github.com/bullet-train-co/bullet_train/pull/730 that I should have pulled into https://github.com/bullet-train-co/bullet_train/pull/892

Re-enable another test for Action Models

---

test/controllers/api/v1/platform/access_tokens_controller_test.rb
test/controllers/api/v1/scaffolding/completely_concrete/tangible_things_controller_test.rb

Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/252

Use new API attribute method in controller tests

---

app/views/account/shared/_menu.html.erb
test/system/application_platform_test.rb
test/system/webhooks_system_test.rb

Closes https://github.com/bullet-train-co/bullet_train-core/issues/272.
Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/299

Add option to hide developer menu

---

test/application_system_test_case.rb
test/system/account_management_test.rb
test/system/account_test.rb
test/system/action_models_test.rb
test/system/application_platform_test.rb
test/system/authentication_test.rb
test/system/bullet_train_gems/audit_logs/super_scaffolding_test.rb
test/system/fields_test.rb
test/system/invitation_details_test.rb
test/system/invitations_test.rb
test/system/membership_test.rb
test/system/pagination_test.rb
test/system/reactivity_system_test.rb
test/system/super_scaffolding_partial_test.rb
test/system/super_scaffolding_test.rb
test/system/tangible_thing_test.rb
test/system/teams_test.rb
test/system/two_factor_authentication_test.rb
test/system/webhooks_system_test.rb

Use `assert_text` and `refute_text` in system tests

---

app/controllers/api/v1/invitations_controller.rb
app/models/ability.rb
app/views/api/v1/invitations/_invitation.json.jbuilder
app/views/api/v1/open_api/index.yaml.erb
app/views/api/v1/open_api/invitations/_paths.yaml.erb
test/factories/invitations.rb

Implements memberships API and adds OpenAPI specs.
Required by https://github.com/bullet-train-co/bullet_train-core/pull/257
Not sure about this line, please correct me if I did it wrong: https://github.com/bullet-train-co/bullet_train/blob/e7133604d0fddc6c797626e3cdf255038ad367e2/app/models/ability.rb#L20

Invitations API

---

config/routes.rb

Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/502

Remove bullet train webhooks routing

---

test/system/resolver_system_test.rb

Fix resolver test for ejected partial

---

test/system/account_management_test.rb
test/system/account_test.rb

Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/546

Update account management tests for changing email

---

config/initializers/exceptions.rb
test/system/teams_test.rb

Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/575

Add last team exception and team system test for Membership foreign constraint

---

test/application_system_test_case.rb
test/system/account_management_test.rb
test/system/application_platform_test.rb
test/system/authentication_test.rb
test/system/dates_helper_test.rb
test/system/invitation_lists_test.rb
test/system/invitations_test.rb
test/system/membership_test.rb

A proposal for taking https://github.com/bullet-train-co/bullet_train/pull/1018 a little bit further. (Note that this PR targets the branch for that PR, and not `main` directly.)

Switch all tests to new names and provide deprecation warnings about old names

---

test/application_system_test_case.rb
test/system/account_management_test.rb
test/system/application_platform_test.rb
test/system/authentication_test.rb
test/system/dates_helper_test.rb
test/system/fields_test.rb
test/system/invitation_lists_test.rb
test/system/invitations_test.rb
test/system/membership_test.rb

Opening this in an effort to close #990 and #1007.

Write more precise routing in system tests

---

config/initializers/exceptions.rb

Opening in favor of #1040.
Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/580

Remove exceptions initializer

---

.circleci/config.yml
test/system/account_management_test.rb
test/system/account_test.rb
test/system/application_platform_test.rb
test/system/authentication_test.rb
test/system/dates_helper_test.rb
test/system/fields_test.rb
test/system/invitation_details_test.rb
test/system/invitation_lists_test.rb
test/system/invitations_test.rb
test/system/membership_test.rb
test/system/reactivity_system_test.rb
test/system/tangible_thing_test.rb
test/system/teams_test.rb
test/system/two_factor_authentication_test.rb
test/system/webhooks_system_test.rb

Follow up to https://github.com/bullet-train-co/bullet_train/pull/720

Run `bin/update/system_tests/use_device_test` in Bullet Train

---

test/bin/setup-action-models-system-test

Related to https://github.com/bullet-train-co/bullet_train/pull/1030

Don't explicitly generate models during ActionModel test setup

---

app/javascript/controllers/index.js
app/views/public/home/index.html.erb
package.json
test/application_system_test_case.rb
yarn.lock

Closes [#615.](https://github.com/bullet-train-co/bullet_train-core/issues/615)
To view the page:
1. Comment out `include RootRedirect` in the [home controller](https://github.com/bullet-train-co/bullet_train/blob/main/app/controllers/public/home_controller.rb).
2. Add an `index` action in the same controller.
Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/628
https://github.com/bullet-train-co/bullet_train/assets/10546292/3bb3240a-0627-42c8-be12-899a8eb7ff05

Implement home page

---

db/migrate/20211130142547_rename_roles_to_role_ids.rb

Run Collaborator related migrations only when the model is present

---

bin/super-scaffold
test/bin/setup-super-scaffolding-system-test

Finishes some tasks in https://github.com/bullet-train-co/bullet_train-core/issues/662.

Update tests with `rails generate super_scaffold` and add deprecation warning

---

Gemfile
Gemfile.lock

Fixes error in Depfu branch #1313.

Fix bootsnap caching error for Depfu bundler dependencies (2024-01-31)

---

config/initializers/bullet_train.rb

Disable strong passwords by default in development

---

test/system/reactivity_system_test.rb

Visit Creative Concepts page directly in reactivity system test

---

config/environments/development.rb

whitelist ngrok-free.app domain in config.hosts

---

config/initializers/devise.rb
db/migrate/20240123092400_add_lockable_to_devise_users.rb
db/schema.rb
test/mailers/previews/devise_mailer_preview.rb

Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/754

Enable devise lockable by default

---

.circleci/config.yml
.github/FUNDING.yml
.redocly.yaml
README.example.md
README.md
app.json
app/views/account/teams/show.html.erb
config/application.rb
config/cable.yml
config/database.yml
config/environments/production.rb
config/initializers/session_store.rb
config/locales/en/application.en.yml
config/locales/en/user_mailer.en.yml
zapier/package.json

Not sure if this will ultimately be how we resolve this, but I'm going to go ahead and merge it since it's currently impossible to start a new project from the starter repo.

Reverting a couple of accidental pushes to main

---

.circleci/config.yml
.github/FUNDING.yml
.redocly.yaml
README.example.md
README.md
app.json
app/views/account/teams/show.html.erb
config/application.rb
config/cable.yml
config/database.yml
config/environments/production.rb
config/initializers/session_store.rb
config/locales/en/application.en.yml
config/locales/en/user_mailer.en.yml
zapier/package.json

This reverts commit 0f740e8460b32ba850e9652b0e086cd8d0140897.
This snuck in via the following sequence of events:
* Some commits were accidentally pushed to `main`
* A PR rebased against main, pulling in those commits
* We undid the bad commits via a reset and force push sequence (I don't know the exact details)
* I merged the PR with the bad commits without re-reviewing it thoroughly

Revert some commits that were accidentally included in a PR

---

app/views/public/home/index.html.erb

A redo of https://github.com/bullet-train-co/bullet_train/pull/1390 without some unwanted commits.

Fix: Typo in `public/home/index.html.erb`

---

.gitignore
package.json

https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

Fix git ignores for new yarn

---

gitpod.Dockerfile

This fix closes #1427. Previous problems seen in #1427 seem to have been fixed on the gitpod side of things

Update gitpod.Dockerfile to ruby version 3.3.1

---

test/application_system_test_case.rb
test/system/invitation_lists_test.rb

Joint PR:
https://github.com/bullet-train-co/bullet_train-core/pull/919

Update test helpers to allow a field label to be wrapped in a div

---

.gitpod.yml
gitpod.Dockerfile

Updates the Gitpod Dockerfile and Gitpod startup scripts so that Gitpod boots seamlessly.

Update Gitpod setup

---

bin/configure
bin/configure-scripts/deploy-buttons/heroku.md
bin/configure-scripts/deploy-buttons/render.md
bin/configure-scripts/deploy_button_heroku.rb
bin/configure-scripts/deploy_button_render.rb

Reverts bullet-train-co/bullet_train#1727

Revert "Remove addition of deploy buttons from `bin/configure`"

---

README.md

This will make BT more accessible by showing beginners and curious devs to see things working in production and show their app to others without upfront investment.

Show how to run BT on Render for free

---

.github/workflows/_deploy_heroku.yml

Hopefully this is temporary and the `heroku-deploy` action will eventually handle this for us.
https://github.com/AkhileshNS/heroku-deploy/issues/188

Install the heroku CLI before deploying to heroku

---

bin/setup
bin/setup-scripts/skip_icu.rb

Fixes https://github.com/bullet-train-co/bullet_train/issues/1849

Skip setup process for icu4c if we don't have bullet_train-conversations

---

.github/workflows/ci-cd-pipeline-main.yml
.github/workflows/ci-cd-pipeline.yml

Fixes https://github.com/bullet-train-co/bullet_train/issues/1816

Fix the confusing workflow diagram when deployment is enabled

---

config/routes.rb

Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/1013

Document the fact that apps can declare their own root routes

---

Gemfile.lock

```
bundle locak --add-platform aarch64-linux
```

Add aarch64-linux as a supported platform

---

.github/workflows/_run_super_scaffolding_tests.yml
.github/workflows/_run_tests.yml

Check for the existence of error screenshots and what not before trying to upload them.
Fixes: https://github.com/bullet-train-co/bullet_train/issues/2189

Quieter CI
