bullet-train-co/bullet_train

bin/configure

Developers running on Linux will get an error when the script tries to open `https://github.com/new` causing the script to stop.
I'm not sure if there's already a gem out there like this, but I just made a small one to take care of this in case we want to use it in the future since I've run into some OS terminal differences in the past:
[Terminal Commands](https://github.com/gazayas/terminal_commands)
All we'd have to do is write the following after adding it to the Gemfile:
```Ruby
require `terminal_commands`
TerminalCommands.open_file_or_link("https://github.com/new")
```

Open link in `bin/configure` depending on OS

---

bin/configure

With clean copy of repository `bin/configure` shows an `mv` error caused by invalid filename. 
```
[...]
Moving `./README.md.example` to `./README.md`.
mv: cannot stat './README.md.example': No such file or directory
[...]
```
Issue is caused by name typo as the file is named `README.example.md`, not `README.md.example`.
resolves #11

Change README example filename in bin/configure

---

Gemfile
Gemfile.lock
test/system/dates_helper_test.rb

Rails ships with [TimeHelpers](https://api.rubyonrails.org/classes/ActiveSupport/Testing/TimeHelpers.html),
so I'm not sure that additional dependecy is necessary.
This commit removes `timecop` gem and uses rails time helpers for time
traveling.

Remove `Timecop` dependecy

---

bin/setup

Shows up like so in the terminal:
```
== Copying `config/application.yml.example` to `config/application.yml`. ==
== Checking Redis connection ==
You are connected to 1 server.
== Restarting application server ==
```
I used the backticks here instead of `system!` to save the output to a string.
Also, I had trouble requiring `colorize` or another file that housed the color-related methods, so I ended up putting `red` in the same file for now.

Add Redis connection check in bin/setup

---

bin/configure
config/application.rb

・Addresses the TODO in `config/application.rb`
I went with the naming convention already used in `bin/configure` and changed `bullettrain` to `untitled_application`.
As a side note, I have also addressed `sanitized_allowed_protocols` [here](https://github.com/bullet-train-co/bullet-train-tailwind-css/pull/580) in the second part of the details.

Set name in `config/application.rb` via initial setup

---

app/javascript/controllers/index.js

In controllers/index, context is called when it should be controllersContext.
This causes an error when using Stimulus.

Fixes typo in Stimulus controllers/index

---

app/javascript/controllers/index.js

Doing this to force CI run for https://github.com/bullet-train-co/bullet_train/pull/51 .

Fixes typo in controllers/index from context to controllersContext (#51)

---

esbuild.config.js

This is needed after installing FontAwesome Pro. Otherwise the esbuild fails.
See the following screenshot for the encountered error:

Added missing loader for woff2.

---

render.yaml

・Address the TODO in `render.yaml`
[Here are the docs](https://render.com/docs/blueprint-spec#access-control) that specifically talk about this.
Since setting this to `everywhere` could potentially be a security issue, setting this value to `[]` allows only internal connections to access the Redis instance.

Limit access to internal connections only in Render Redis instance

---

test/system/webhooks_system_test.rb
test/test_helper.rb

・Fixes the `NoMethodError` caused by `current_email.click_link` 
This inherently had to do with a Rails issue which I talked about [here](https://github.com/bullet-train-co/bullet-train/pull/441) a while back. I also mention the problem with `current_email` [here](https://github.com/bullet-train-co/bullet-train-tailwind-css/issues/562).
I wrestled with this for a while and ultimately came up with this solution. I’m not sure if Rails has simply made an update to fix the issue (there’s nothing mentioned in the issue itself about an official fix), but using `Sidekiq::inline!` in `test/test_helper.rb` consistently made the Invitation system test pass.
This caused the webhooks system test to fail though. It was the only system test that used the fix proposed in the Rails issue which we …

Fix the `NoMethodError` caused by `current_email.click_link` 

---

app.json

When deploying to Heroku for the first time, there's no need to start with a paid Rails Autoscale plan. The free plan supports 20 autoscale events per month at any scale, and will prompt if there is a need to upgrade.

Use the free version of Rails Autoscale

---

db/migrate/20220418034147_drop_imports_csv_imports.rb
db/schema.rb

Closes #69.
[Joint PR](https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/25)
There weren't any classes under `app/model`, so I think we'll be okay just dropping the table with a migration. I did however adjust some tests in `bullet_train-super_scaffolding`, so you can find those changes in the joint PR.

Remove CSV Imports table

---

Gemfile
Gemfile.lock
config/application.rb
config/environments/test.rb
test/application_system_test_case.rb

Carry over from [this PR](https://github.com/bullet-train-co/bullet-train-tailwind-css/pull/580) in the tailwind repo.

Address test deprecations

---

.gitignore

- gitignore `.yalc` and `yalc.lock`
- everything else is handled by `bin/develop`. See https://github.com/bullet-train-co/bullet_train-base/pull/37

Prepare for using `yalc link` instead of using `yarn link` for local npm packages

---

app/controllers/account/teams_controller.rb
app/helpers/application_helper.rb
config/initializers/pagy.rb
test/system/pagination_test.rb

・Closes #47.
Add the following to `config/application.yml`:
```yml
PAGY: true
```
Add the following packages to the Gemfile:
```ruby
gem "bullet_train", git: "git@github.com:bullet-train-co/bullet_train-base.git", branch: "features/pagy-for-web-ui"
gem "bullet_train-super_scaffolding", git: "git@github.com:bullet-train-co/bullet_train-super_scaffolding.git", branch: "features/pagy-for-web-ui"
```
Now we can paginate Tangible Things and Super Scaffolded Models.
The default is 20 items per page, but I've set `Pagy::DEFAULT[:items]` to 3 in the initializer to make it easy to look at here.
The buttons to change pages could use some work, but since there's a lot going on with the Bullet Train themes currently, I've left them as is for now.
The index partial for Super Scaffolded models is …

Enable pagination for Web UI

---

esbuild.config.js

Addresses [this issue](https://github.com/bullet-train-co/bullet_train-themes-light/issues/7) in the `bullet_train-themes-light` repository.
This unfortunately is a problem other people are having that hasn't seemingly been solved yet. I'm not entirely sure what's going on here, and I don't think these answers are ideal, but angular-cli for example just decided to silence the warning ([Pull Request here](https://github.com/angular/angular-cli/pull/22098)), and [this issue](https://github.com/vitejs/vite/issues/6333) in vitejs just shows people silencing the warning (and also showing concern for not addressing the root cause).
I guess it's just a matter of wanting to keep the warning present until it gets fixed by a third-party library, or to just silence the warnings like I have proposed …

Silence esbuild warnings

---

.circleci/db_schema_check

This is the fix by itself for outputting `db/schema.rb`'s git diff.

Update the CircleCI `db/schema.rb` check to output the diff on fail

---

bin/configure
bin/setup

When initially making a Bullet Train application, developers run the following commands:
`bin/configure`
`bin/setup`
However, unit tests will fail if they haven't run `bin/dev` yet because the assets haven't been compiled yet.
This step compiles the assets in the configure step so developers don't get confused in case they try to run tests before ever starting the server, assuming that things are broken.

Build assets in `bin/configure`

---

Procfile.dev
bin/theme
package.json
postcss.mailer.config.js
yarn.lock

Builds a separate `application.mailer.light.css` file with css variables replaced using `postcss-css-variables`, so we can use Tailwind styles as safely as possible in mailer views.
Note, not all Tailwind classes will work, as some will rely on css variables, but not all CSS works in many mail clients anyway, so care should still be taken when designing email HTML - don't just assume all Tailwind styles will behave how you expect.
Also allowed the theme to have an optional separate `tailwind.mailer.#{theme}.config.js` - premailer inlines all styles from media queries, to the light theme's dark styles would always be rendered inline, making all emails dark themed. This seems wrong, so in the light theme in https://github.com/bullet-train-co/bullet_train-themes-light/pull/10 the dark theme …

Build mailer css in a separate file with css variables replaced

---

bin/configure

We check if yarn is installed with this block earlier on line 121:
```ruby
if `yarn -v 2> /dev/null`.length > 0
puts green "Yarn is installed."
else
puts red "You don't have Yarn installed. We can't proceed without it. Try `brew install yarn` or see the installation instructions at https://yarnpkg.com/getting-started/install ."
exit
end
```

Remove extra yarn install check

---

.circleci/config.yml
Gemfile
test/application_system_test_case.rb
test/support/ferrum_console_logger.rb
test/system/fields_test.rb
test/system/invitation_details_test.rb
test/system/invitations_test.rb
test/system/membership_test.rb
test/system/reactivity_system_test.rb
test/system/webhooks_system_test.rb

This PR switches the backend for system tests to use [Cuprite](https://github.com/rubycdp/cuprite) as a more reliable alternative to Selenium.  It is generally drop-in.  There are a few differences in the driver API that required some updates to the test code:
- Accessing browser console logs (for `assert_no_js_errors`) requires a custom logger (based on https://github.com/rubycdp/cuprite/issues/113#issuecomment-753598305)
- Cuprite doesn't support `page.driver.browser.switch_to.alert.accept`, but we can use the generic Capybara `accept_alert` instead
- I updated the code for typing in select2 elements, moving from send_keys to `page.driver.browser.keyboard.type`

Switch system tests to Cuprite

---

Gemfile

I'm assuming we don't need these lines anymore since we merged in [nice_partials#28](https://github.com/bullet-train-co/nice_partials/pull/28)
Thanks @kaspth!

Delete unneeded comment (xray-rails) in Gemfile

---

bin/configure

Context: https://discord.com/channels/836637622432170028/836637623048601633/996487503286644757
As you can see in the comment, `./.ruby-version` had a value of `ruby-3.1.2`:
```
Bullet Train requires Ruby ruby-3.1.2 and ruby -v returns ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21].
Try proceeding with with Ruby ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21] anyway? [y]
```
rbenv simply writes `3.1.2` so it worked for anyone using rbenv, but rvm was breaking so I edited the code here so it's compatible with rvm as well.
[Here's a Jetbrains post](https://www.jetbrains.com/help/ruby/ruby-version-managers.html#auto_switch) that shows rvm writes Ruby versions like `ruby-3.1.2`.

Read Ruby version correctly when using rvm

---

.circleci/config.yml

This PR adds Knapsack to the Cuprite system test run to improve speed.

Use Knapsack for Cuprite tests

---

test/system/fields_test.rb
test/system/invitations_test.rb
test/system/reactivity_system_test.rb
test/system/tangible_thing_test.rb

Closes #300.
`"Don't have an account?"` shouldn't be present on the sign in page in invitation-only mode, but we didn't have a hook in the tests to check this. This PR takes care of the three test files which just include a one-liner, along with the invitations system test.
This file took a little more work than the other three files. There are a lot of diffs, but most of it is because I wrapped the test logic in an `unless invitation_only?` block. That way the test skips adding a new team, since we can't add a new team in invitation-only mode, if my understanding is correct.
I also removed this block:
```ruby
if invitation_only?
assert page.has_content?("Creating new teams is currently limited")
be_invited_to_sign_up
end
```
The test was failing before we got here because `Add New Team` …

Adjust invitations system test

---

app/views/layouts/_head.html.erb

Closes #219.
However, when actually trying to save the resource after uploading the image, I get the following error (I named the model `Pic`):
```
ActiveSupport::MessageVerifier::InvalidSignature in Account::PicsController#create
```
Maybe I'm not creating the model correctly, but if this is legitimately a bug I can look into this too and open a separate PR.
Thanks for reporting, @malachaifrazier!

Update cloudinary widget

---

test/bin/setup-super-scaffolding-system-test

Removing these workarounds since [bullet_train-super_scaffolding#31](https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/31) was merged.

Remove bug workaround in Super Scaffolding system test setup

---

README.example.md

Right now `18.6.0` is specified in `.nvmrc`.

Update Node version in Readme

---

test/controllers/api/v1/webhooks/outgoing/endpoints_endpoint_test.rb
test/system/webhooks_system_test.rb

Now only properly formatted urls are accepted, so change test to use one.

Fix webhook API test

---

Gemfile
config/initializers/theme.rb
test/system/account_test.rb
test/system/authentication_test.rb

Addresses the TODO in the Gemfile concerning the devise gem.
Joint PRs
- https://github.com/bullet-train-co/bullet_train-themes/pull/15
- https://github.com/bullet-train-co/bullet_train-themes-light/pull/46
The main fix is in a monkey patch if the first joint PR.
I had to adjust the tests because `"Password"` was turning into `"password"` in a couple of flash notices, but I'm not entirely sure why it's happening. I can look into that side more if necessary.

Address devise gem placement issue in Gemfile

---

app/controllers/application_controller.rb

Address the TODO in [bullet_train-base/app/controllers/sessions/controller_base.rb](https://github.com/bullet-train-co/bullet_train-base/blob/88573750c8e519aff0a4a2bacf07c2dd12e611cd/app/controllers/concerns/sessions/controller_base.rb)
Joint PR
- https://github.com/bullet-train-co/bullet_train-base/pull/96
We were including `protect_from_forgery` in our application, but we were still getting this error without the workaround in `bullet_train-base`:
```
ActionController::InvalidAuthenticityToken (Can't verify CSRF token authenticity.)
```
I sifted through devise's issues and the general consensus was that it wasn't an issue with devise. However, they had some different fixes. Unfortunately, they didn't work for me:
- `> rails dev:cache`
- Revert to rack `2.2.2`
- Remove …

Ensure forgery protection callback runs first

---

app/javascript/application.js

I was referencing the upstream repo and noticed that `jstz` was imported into `application.js` twice: [here](https://github.com/bullet-train-co/bullet_train/blob/main/app/javascript/application.js#L20) and [here](https://github.com/bullet-train-co/bullet_train/blob/main/app/javascript/application.js#L28-L30). This change just removes the duplicate import & global assignment.

removes duplicate jstz entry in application.js

---

app/models/ability.rb

Looking through our current Bullet Train packages, I don't see `@user_ability.can?(:dashboard, @user)` or anything like it show up anywhere, so I think we're safe to delete this one.
There weren't any tests in `test/models/ability_test.rb` either, so we don't need to adjust our tests.
The only place I figured MIGHT get affected is `config/initializers/rails_admin.rb` in `bullet_train-platform`, but it doesn't seem like it's being used so I think we're ok.

Delete unneeded ability

---

bin/dev

I'm curious if this is an M1 issue or if it has actually been fixed, because I updated tmux to 3.3a on my mac (not M1) with brew and it's working for me. Thought I'd open this PR in case it started working for anyone else too.

Re-enable overmind

---

bin/theme

Context: https://discord.com/channels/836637622432170028/836637623048601633/1008367566894403644
Most of our scripts are run manually, but `bin/theme` is run whenever we run the commands in `Procfile.dev`.
`./package.json`:
```js
"scripts": {
"build": "node esbuild.config.js",
"build:css": "bin/link; yarn light:build; yarn light:build:css; yarn light:build:mailer:css",
"light:build": "esbuild `bundle exec bin/theme javascript light` --bundle --sourcemap --outdir=app/assets/builds --loader:.png=file --loader:.jpg=file",
"light:build:css": "NODE_PATH=./node_modules tailwindcss -c `bundle exec bin/theme tailwind-config light` -i `bundle exec bin/theme tailwind-stylesheet light` -o ./app/assets/builds/application.light.css --postcss ./postcss.config.js",
"light:build:mailer:css": …
```

Remove `pry` in theme script

---

test/application_system_test_case.rb
test/system/animations_test.rb

Fixes https://github.com/bullet-train-co/bullet_train-base/issues/63
See co-dependent PRs:
- https://github.com/bullet-train-co/bullet_train-themes-light/pull/29
- https://github.com/bullet-train-co/bullet_train-base/pull/79
This PR deals with the testing coverage:

Fix mobile menu breaking after repeated reveal/hide: Add test coverage

---

.circleci/config.yml

I was about to close #176 when I noticed we hadn't updated the CircleCI image for the system tests with Cuprite. Besides that, we should have all of the images updated here on the starter repo.

Update CircleCI image for system tests with Cuprite

---

config/initializers/devise.rb

Closes #319.
Joint PR
- https://github.com/bullet-train-co/bullet_train-base/pull/86
It seems that we just didn't have the rememberable module enabled in the first place, so I updated the new session view over in `bullet_train-base`.

Enable Devise rememberable module

---

test/system/animations_test.rb

Addresses the TODO in `test/system/animations_test.rb`
Cuprite doesn't currently support `obscured?`
The method that was giving us a problem was `obscured?` from this line:
```ruby
assert_not els[:open_button].obscured?, "open_button should not initially be obscured on iteration #{i}"
```
Since Capybara can use different drivers, it initially calls this general method from [Capybara::Node::Element](https://github.com/teamcapybara/capybara/blob/b8705059b142930e97fcbd8f34b9409755570c44/lib/capybara/node/element.rb#L316):
```ruby
def obscured?
synchronize { base.obscured? }
end
```
Prying here and checking out `base`, we get the following results.
```
> base
#=> #<Capybara::Selenium::ChromeNode tag="button" path="/HTML/BODY[1]/DIV[2]/DIV[1]/DIV[3]/MAIN[1]/DIV[1]/BUTTON[1]">
> base.class
#=> …
```

Update comment concerning failing Cuprite test

---

app.json

Issue described in #489.
It turns out the free version of the addon is now(?) called `basic` rather than `free`

Update app.json to reference correct honeybadger addon name

---

bin/dev

Extraneous foreman call in bin/dev cause foreman to run again after the initial overmind or foreman process is killed.

Remove extraneous foreman call in bin/dev

---

test/application_system_test_case.rb

ref: https://github.com/rubycdp/cuprite/commit/682c723b26b7e949df5cba4c4eec302b0d1a20bf

Fix: Cuprite logger is defined in options

---

.gitignore
bin/secrets

Example output:
```
andrewculver@Andrews-MacBook-Air bullet_train % bin/secrets
DEVELOPMENT
Generating secret key and encrypted credentials for development.
Generating encrypted keys for Active Record Encryption in development.
File encrypted and saved.
The encryption key for the development environment is stored in `config/credentials/development.key` and will not be (and should not be) committed to the repository. Store this somewhere safe and only share it with team members who you trust with your encrypted credentials for the development environment.
To edit the encrypted credentials for development with VS Code (for example), run:
EDITOR='code --wait' bin/rails credentials:edit --environment development
TEST
Generating secret key and encrypted credentials for test.
Generating …
```

Add `bin/secrets` to help configure encrypted secrets.

---

app/views/api/v1/open_api/index.yaml.erb

Updates the OpenAPI documentation to the cursor pagination used now in `bullet_train-api`

Feature: Added pagination headers and parameters to OpenAPI index.yaml.erb

---

config/initializers/mime_types.rb
test/controllers/api/test.rb

There were still a few lines related to JSON API that we don't need anymore, so I deleted them.
I poked around just to make sure there wasn't anything else, but I think that's it. I thought the `to_json_api` method we have in `bullet_train-base` might need to be edited, but we definitely need it get parse the object correctly.

Remove JSON API related code

---

Gemfile.lock
app/views/api/v1/open_api/index.yaml.erb

Closes 2nd part of https://github.com/bullet-train-co/bullet_train-outgoing_webhooks/issues/12
I assume tests should pass after https://github.com/bullet-train-co/bullet_train-outgoing_webhooks/pull/16 is merged.

Add Webhooks::Outgoing::Endpoint to OpenAPI documentation

---

render.yaml

Closes #509.
For some reason, if we just use `bundle install` for the Sidekiq worker's build command, this won't read all of the assets that we should have available in the pipeline, resulting in a missing file error when trying to run a background job
As you can see in [this post in the Render community](https://community.render.com/t/rails-worker-cant-find-assets/4885), other people are running into the same issue where their assets are missing, so they fixed it by changing their worker's build command to
`bundle install && bundle exec rake assets:precompile && bundle exec rake assets:clean`.
This is also showing up in other example blueprints
[Example 1](https://binarysolo.chapter24.blog/deploy-rails-and-sidekiq-to-render-com-using-yaml)
[Example …

Precompile and clean assets on Render worker's build command

---

.standard.yml
Gemfile.lock

1. Run `bundle update`
2. Ignore `Lint/UselessAssignment` check for Ruby Standard

Update gems for use with Ruby 3.2.0

---

package.json
yarn.lock

Without yalc in the starter repository, we won't be able to reset the npm packages properly.
```
> bin/hack --clean-js
Resetting packages to their original path
yarn run v1.22.19
error Command "yalc" not found.
```
```
> bin/hack --clean-js
Resetting packages to their original path
yarn run v1.22.19
$ /home/gazayas/work/bt/bullet_train/node_modules/.bin/yalc remove @bullet-train/bullet-train
Removing installation of @bullet-train/bullet-train in /home/gazayas/work/bt/bullet_train
Done in 0.26s.
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
...
```

Add yalc for use with `bin/hack`

---

package.json
tailwind.config.js

Fixes #439 
This PR builds on the `execSync` technique introduced by @KonnorRogers in #521 for running `bin/theme` inside a local `tailwind.config.js` file for loading the current theme's tailwind config file and allowing overrides.
* Adds a local `tailwind.config.js`
* Modified `package.json` to load local `tailwind.config.js` with `THEME=\"light\"` ENV var set
* Shows example overrides in local `tailwind.config.js`

Allow theme tailwind.config.js overrides

---

gitpod.Dockerfile

Closes #560.
We were getting the error because Sidekiq 7 needs Redis 6 to work, but Gitpod was installing v5.0.7.
This is how you install Redis according to [Gitpod's docs](https://www.gitpod.io/guides/gitpodify#redis):
```Dockerfile
FROM gitpod/workspace-full
RUN sudo apt-get update \
&& sudo apt-get install -y \
redis-server \
&& sudo rm -rf /var/lib/apt/lists/*
```
Besides the `gitpod/workspace-full` line, we had everything written correctly. Using `gitpod/workspace-full` doesn't allow us to use our Postgres database, and it doesn't update to the latest version of Redis either.
I thought it would be best to download the latest stable version, so I'm not pulling Redis from the latest development branch. Also, the original command only installs `redis-server`, but if you install `redis` …

Edit commands to install Redis for Gitpod

---

Gemfile.lock

Trying to run anything in the terminal yields the following error:
```
> rails c
Could not find nokogiri-1.13.10-x86_64-linux in locally installed gems
Run `bundle install` to install missing gems.
```
Just had to run `bundle install` and everything started to work as normal.
Details here in the Nokogiri repository: https://github.com/sparklemotion/nokogiri/issues/2740

Update Gemfile.lock for compatibility with Linux

---

bin/configure

On my first time using of Bullet Train, I've opened an issue #607 where I could resolve later the same day. 
I must have put an empty string for some reason when prompted about the name of an application which caused that issue. 
This PR is to prevent this problem if it occurs.
Also I have added `[y/n]` on the first question prompt.

update `bin/configure` to prohibit empty application name

---

bin/configure

I think it would be better to have the options `[y/n]` being asked more consistently when needed.

update `bin/configure` to standardize ask prompts with `[y/n]`

---

config/application.rb

Addresses the TODO in `config/application.rb` about extracting code in the `config.to_prepare` block to `bullet_train-api`.
Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/93
You can see that we still get the devise layout string after loading the environment:
```
> rails c
Loading development environment (Rails 7.0.4)
irb(main):001:0> Doorkeeper::ApplicationController._layout
=> "devise"
```
Also, the code in the monkey patched class is only loaded when calling ` BulletTrain::Api.set_configuration(self)` which I've added here.

Extract Doorkeeper config settings to `bullet_train-api`

---

test/controllers/account/scaffolding/completely_concrete/tangible_things_controller_test.rb
test/system/dates_helper_test.rb
test/system/super_scaffolding_partial_test.rb
test/system/super_scaffolding_test.rb
test/system/tangible_thing_test.rb
test/system/webhooks_system_test.rb

These are the tests for https://github.com/bullet-train-co/bullet_train-core/pull/49.
I also fixed a small bug in the Super Scaffolding Partial system test along the way.
These fixes mostly consist of:
1. Clicking "Back" so we can continue the system tests on the model's index page.
2. Deleting unneeded clicks which had no assertions after them inside the Super Scaffolding system test.
I think developers will need to change their tests for Super Scaffolded models, specifically for anything generated by `test/controllers/account/scaffolding/completely_concrete/tangible_things_controller_test.rb`.

Tests for redirecting to show page for new records

---

.standard.yml

The bug in https://github.com/testdouble/standard/issues/497 has been fixed, so we don't need to ignore these files in `.standard.yml` anymore.
Here are the files where `disable` is being used:
```
> git grep standard:disable
config/routes.rb:  collection_actions = [:index, :new, :create] # standard:disable Lint/UselessAssignment
config/routes/api/v1.rb:collection_actions = [:index, :new, :create] # standard:disable Lint/UselessAssignment
```

Remove unneeded ignore lines in `.standard.yml`

---

Gemfile
Gemfile.lock

Our tests are passing for the official release of `active_hash`, so we don't need to use our own branch for this anymore.

Update `active_hash` to v3.1.1

---

package.json
yarn.lock

When running `bin/hack --watch-js bullet_train-sortable`, we get the following error when trying to run the server, and then the server just shuts down. To compensate for this, I added a line in the `bin/hack` task which prompts the developer to have their server running before continuing so the server won't shut down. Either way, this error shows up in the logs.
```
js               | ✘ [ERROR] Could not resolve "@rails/request.js"
js               | 
js               |     .yalc/@bullet-train/bullet-train-sortable/app/assets/javascripts/bullet-train.esm.js:1:92:
js               |       1 │ ...";import{post as t}from"@rails/request.js";function a(e){var n=e...
js               |         ╵                           ~~~~~~~~~~~~~~~~~~~
js               | 
js               |   You can mark …
```

Add `@rails/request.js` to starter repository

---

app/controllers/account/teams_controller.rb
app/controllers/account/users_controller.rb

Closes #619
I changed the migration we're working with slightly to make testing easier:
```
rails g migration add_weight_goal_to_teams weight_goal:string
bin/super-scaffold crud-field Team weight_goal:text_field
```
When we Super Scaffold a new attribute, it gets scaffolded to the API controller but not the regular controller. You can tell in this test (`bundle exec rails test test/controllers/account/teams_controller_test.rb:29`) that we handle the strong parameters in [base the API controller in bullet_train-api](https://github.com/bullet-train-co/bullet_train-core/blob/7cf007def6104e2f95a445e218f76148ce249db1/bullet_train-api/app/controllers/concerns/api/v1/teams/controller_base.rb#L6) as expected, but it grabs `permitted_fields` and `permitted_arrays` from the [regular …

Ensure new attributes get Super Scaffolded to `Team` and `User` controllers

---

README.example.md
bin/configure

Context: https://discord.com/channels/836637622432170028/836637623048601633/1024027106189000714
The Render deploy button deploys whichever repo is passed to the `repo` parameter in the link. This PR makes sure the deploy button points to the right repo whenever a developer creates a new Bullet Train application.
The README looks like this after running the script in `bin/configure`.

Edit Render deploy button to deploy per application

---

app/models/user.rb

The bullet_train-roles gem requires this module to be included in the User model.
We didn't notice it was missing before because we were accidentally overloading the methods it adds in the bullet_train-base gem.
We're currently working on an update (https://github.com/bullet-train-co/bullet_train-roles/pull/20) to the roles gem that changes some of the method signatures and breaks the overloaded versions of the methods.  I've added another PR to remove the overloaded methods from the bullet_train-base gem here (https://github.com/bullet-train-co/bullet_train-base/pull/121).
In order to do the update to the roles gem, we need to remove the overloaded versions of the methods _and_ add the required module in to the User class.
We can either add the `Roles::User` module directly to the User …

Add the Roles::User module to User

---

app/views/layouts/_head.html.erb

This doesn't solve #381 completely, but I think it's a step in the right direction.
I don't think this is necessarily a problem with `_box.html.erb` or Chrome, but with iOS. For example, in this video the website still has the scrolling issue even in Safari, but when adding the page to the home screen and scrolling from there (also after adding the meta tag in this PR), there is no bounce/double scroll issue:
https://user-images.githubusercontent.com/10546292/190663041-4991406a-f427-4ea6-8d0f-047acd4d7a44.mov
I'm convinced that it's because we're not minimizing the address bar when we scroll down the page. I'm finding a lot of different suggestions online for minimizing the address bar when scrolling down, but no luck so far.
Here's a comparison with Tailwind's website: …

Use web app capable meta tag for iOS

---

bin/configure

Requiring all of Rails caused issues on my machine because of conflicting gem versions. It's also unnecessary. Requiring `active_support/inflector` is enough to get us going.
```
/Users/carl/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2236:in `raise_if_conflicts': Unable to activate railties-7.0.3.1, because activesupport-7.0.4 conflicts with activesupport (= 7.0.3.1) (Gem::ConflictError)
from /Users/carl/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1367:in `activate'
from /Users/carl/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems.rb:211:in `rescue in try_activate'
from /Users/carl/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems.rb:204:in `try_activate'
from <internal:/Users/carl/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/ke …
```

Require "active_support/inflector" instead of all of Rails

---

Gemfile.lock
config/initializers/devise.rb

Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/123
Looking at the [upgrade guide](https://github.com/heartcombo/devise/wiki/How-To:-Upgrade-to-Devise-4.9.0-%5BHotwire-Turbo-integration%5D), it seems that the change here in the initalizer is the only change we'll need.
These two lines are now added by default in v4.9.0 when running `rails g devise:install`.
We may have to make some changes concerning `data-confirm` and `data-method`, but tests are passing locally for me with https://github.com/bullet-train-co/bullet_train-core/pull/123, so I think we should be okay for now.

Upgrade to Devise 4.9.0

---

Gemfile
Gemfile.lock

On bullet_train-core and other gems, we're seeing CI issues when we're trying to bundle the starter repo Gemfile, which is this issue: https://github.com/ruby/debug/issues/898
Reference build:
https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-core/613/workflows/1ca785a1-60f4-445c-a7b2-826d27ed3cdb/jobs/1855?invite=true#step-111-220

Lock debug to prevent CI issue

---

app/views/api/v1/open_api/index.yaml.erb

All the rest was merged into `bullet_train-outgoing_webhooks` here: https://github.com/bullet-train-co/bullet_train-core/pull/29

Added support for Webhooks::Outgoing::Event to OpenAPI

---

package.json

Closes #744
I was running into a lot of issues with bootsnap, but eventually got things to work on both MacOS and Ubuntu. [This issue here](https://github.com/Shopify/bootsnap/issues/73) talks about cleaning out bootsnap's cache, so if developers are having trouble after using the new syntax, they can refer to that issue if they're getting the same error output.

Fix package.json syntax for running bundle script

---

bin/theme

updates `bin/theme` to work with rails main branch. otherwise it breaks with following stacktrace when running `bin/dev`:
```
15:12:56 light-mailer-css.1 | bundler: failed to load command: bin/theme (bin/theme)
15:12:56 light-mailer-css.1 | bin/theme:36:in `select': undefined method `present?' for "/workspaces/workspace":String (NoMethodError)
15:12:56 light-mailer-css.1 | 
15:12:56 light-mailer-css.1 | @candidate_paths = [Dir.pwd, gem_path].select(&:present?)
15:12:56 light-mailer-css.1 |                                       ^^^^^^^
15:12:56 light-mailer-css.1 | Did you mean?  prepend
15:12:56 light-mailer-css.1 |   from bin/theme:36:in `<top (required)>'
15:12:56 light-mailer-css.1 |   from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
15:12:56 light-mailer-css.1 |   from …
```

Update bin/theme for rails 7.1 compatibility

---

app/views/public/home/index.html.erb

Joint PR:
- https://github.com/bullet-train-co/bullet_train-core/pull/119
Since we give developers the option to use `Public::HomeController`, I thought it would be good to provide the index view for them as well. Here's what it looks like when they comment out `include RootRedirect` in the controller and access `localhost:3000`:

Add public home controller view

---

test/system/action_models_test.rb

We'll have to wait for CableReady v5.0.0 to get rid of the inverse_of error.

Fix the targets-one Action Models test

---

Gemfile

Ruby version (`3.2.1`) is specified in both Gemfile and .ruby-version, these two Ruby versions must be the same in theory. This PR just uses the same Ruby version (in `.ruby-version`) in the `Gemfile` to emphasize the consistency of the Ruby version, which may optimize the development experience a little.

Use the same ruby version in the Gemfile as in the .ruby-version file

---

bin/configure

Resolves bug reported in the BT Discord channel about failing GitHub jobs
- Removes the included GitHub workflow config to merge main into edge in `bin/configure`
- Guards against throwing a failed job error after pushing to GitHub the first time.
Wasn't sure if it made sense to include a prompt before removing so left that out for the time being.

Remove default github workflow file in configure before pushing to github

---

config/application.rb

I think we talked about this a long time ago, maybe even before the Tailwind repository, but an error is raised when we don't fallback to the default locale:
There are some other things I'd like to do with locales, but most of it will most likely take place over at `bullet_train-core`.

Fallback to English for locales

---

.gitignore

We don't want to ignore `.tool-versions`.  It's used by `asdf` to determine which version to use for ruby, nodejs, and others.  Ignoring it would be like ignoring `.ruby-version`.

Update .gitignore to not ignore .tool-versions

---

config/initializers/theme.rb

Addresses #666.
We have more options besides `BulletTrain::Themes::Light.color`, but I don't think we document them anywhere, and I think it makes sense to just comment them out here in the initializer similar to something you'd see in `config/environments/development.rb` for example.
```ruby
```

Add commented-out theme configurations in initializer

---

test/system/application_platform_test.rb

Addresses the TODO in `test/system/application_platform_test.rb`
```
Finished in 37.252439s, 0.0268 runs/s, 0.2148 assertions/s.
1 runs, 8 assertions, 0 failures, 0 errors, 0 skips
```
```
Finished in 21.607441s, 0.0463 runs/s, 0.3702 assertions/s.
1 runs, 8 assertions, 0 failures, 0 errors, 0 skips
```

Speed up Application Platform system test

---

config/models/billing/products.yml

When a YAML parser encounters `nil` it is parsed as the literal string `'nil'`. But when a YAML parser encounters `null` it is parsed as `nil`.
This PR just changes instances of `nil` to `null` in `config/models/produts.yml`.

YAML expects null, not nil

---

config/initializers/doorkeeper.rb

If there's no specific reason to use the `password` grant flow, we probably shouldn't use it because of the security risks that come along with it.
If no grant flows are specified, Doorkeeper automatically sets these values to `authorization_code` and `client_credentials`, so these should be the default values.
`implicit` and `password` have pitfalls to look out for, so I read up on the information provided by the links and paraphrased it to make it somewhat shorter.
The password grant seems to be the most high-risk, so if we don't have a need for it we can probably remove it from `grant_flows`, but I'll leave that up to your discretion.

Document specific details about Doorkeeper grant flows

---

Gemfile
Gemfile.lock

Fixes bullet-train-co/bullet_train/issues/818
Previously the `webdrivers` gem was trying to find a version of Chrome that doesn't exist in the old repository. It seems that Chrome has moved where they publish new versions.
The official recommendation from the `webdrivers` gem authors seems to be to remove the `webdrivers` gem entirely, and update `selenium-webdriver` to the latest version. This PR does that.
This gets system tests running, instead of crashing. But there seems to be on system test that fails, and I don't think it's related to a webdriver issue.
```
validating http://localhost:3001/api/v1/openapi.yaml...
Failed to resolve api definition at http://localhost:3001/api/v1/openapi.yaml:
- request to http://localhost:3001/api/v1/openapi.yaml failed, reason: connect ECONNREFUSED …
```

Remove the webdrivers gem and update selenium-webdriver

---

test/test_helper.rb

When setting the default locale to another language and running the tests, most of the test suite fails because we use a lot of string literals as opposed to I18n's `t` method:
[test/system/account_test.rb:40](https://github.com/bullet-train-co/bullet_train/blob/7ced0b8b8bab4c5a0a56f10c0df091411de69fb9/test/system/account_test.rb#LL40C7-L40C58)
```ruby
assert page.has_content?("Signed in successfully.")
```
Since the behavior of the system tests don't really depend on the what language is being output but on the flow of the system as a whole, I think this a viable way to handle our tests unless we want to replace all the strings with locales in the future.

Set the default testing language to English

---

test/application_system_test_case.rb
test/system/application_platform_test.rb
test/system/invitations_test.rb
test/system/membership_test.rb

We had some duplicate methods in different places in the system tests, so I placed them all in `test/application_system_test_case.rb`.

Move duplicated code to application system test case

---

bin/configure

While installing and configuring bullet_train, I noticed that it told me I didn't have node installed because it was checking whether I had installed it using homebrew. While I use homebrew for services, for language runtimes I use another package manager.
My thinking is that just directly checking if node is installed and that it's the right version is a somewhat user-friendlier approach, and that it matches how you handle the ruby version.
I moved the yarn check below the node check and now also fail if node isn't installed because I think this is probably the intended behavior if you're actually checking for presence of the runtime.
This is my first PR so please let me know if this type of PR is welcome and if I need to know anything else with respect to contributing.

Directly check if node is installed in bin/configure

---

Gemfile
Gemfile.lock

The issue over at `debug` is now closed and we're using Ruby 3.2.2, so I removed the version restriction.

Remove version restriction for the debug gem

---

esbuild.config.js

I added a file to `app/javascript/entrypoints` and I couldn't start the server.
```js
// app/javascript/entrypoints/react.js
console.log("asd");
```
I got this error:
```
js        | Started with pid 42609...
yarn run v1.22.17
yarn run v1.22.17
$ THEME="light" node esbuild.config.js --watch
$ THEME="light" NODE_PATH=./node_modules tailwindcss -c tailwind.config.js -i $(bundle exec bin/theme tailwind-stylesheet light) -o ./app/assets/builds/application.light.css --postcss ./postcss.config.js --watch
js        | ✘ [ERROR] Cannot read directory "app/javascript/entrypoints/react.js": not a directory
js        |
js        | ✘ [ERROR] Cannot read directory "app/javascript/entrypoints/react.js": not a directory
js        |
js        | ✘ [ERROR] Could not resolve …
```

Fix: Properly assign entrypoints key-value pairs

---

app/javascript/controllers/index.js

To help debug Stimulus controllers, this PR adds `window.Stimulus` and a comment to hint on two common ways to use it (debugging events and finding the list of loaded controllers).
It's arguably safe to use in production, unless Stimulus controllers expose methods that access resources that aren't protected by the application, which should be dealt with at the application level.

Add window.Stimulus for help debugging, even in production

---

bin/setup

`yarn check` has been removed in Yarn v2, running this command only outputs a warning now. 
Closes #781

Fix check warning with yarn 2.x in bin/setup

---

test/system/resolver_system_test.rb

Since `bin/resolve` depends on the gem installation path and gem version to return the proper result, we use `bundle show` to get the gem's proper path.
https://github.com/bullet-train-co/bullet_train-core/pull/350 uses mock strings to test resolving for annotated paths like ``, and although we can use `bundle show` to access some of the gems in that directory, we don't have access to ones like `bullet_train-themes-light`.
This presents two issues for me. Writing tests long-term, I think that:
1. The tests should have knowledge of the environment so when we test the other functionalities of `bin/resolve`, we can write tests like the one I have written in this PR.
2. Because of that I would rather not split the tests between two different repositories, so I think it would be beneficial to …

Add resolver test for partial invocation string

---

config/initializers/bullet_train.rb

We have a `BulletTrain::Configuration` class, but we don't implement it in any of our initializers, so I added one here.
Joint PR:
- https://github.com/bullet-train-co/bullet_train-core/pull/208

Add initializer for Bullet Train configuration

---

app/views/account/shared/_menu.html.erb

https://github.com/bullet-train-co/bullet_train/issues/580
Issue:
The UI for the drop-down menu was broken as shown above because `@menu_orientation` was coming as `top` instead of `side`. The following hack has fixed the issue but I am not sure if this is the correct approach to fix this issue. 
Fixed:

Fix Drop Down Menu for Integration

---

app/views/account/shared/_menu.html.erb

I noticed after I merged #615 (😬 🤦‍♂️) that the tests in `main` were failing. It turns out that having the assignments for `@menu_orientation` inside of the `capture` block made it so that we didn't capture the `render` call, but instead we seem to capture a `nil`. I think this is because that final assignment returns nothing to the template. This moves the assignments outside of the `capture` block.
Fixes #829

Bug fix for #615

---

Procfile.dev
README.md
bin/set-ngrok-url
config/environments/development.rb

With the price increase of the ngrok paid plan, I thought it would be nice to add some ways to leverage the free account easier.
Running ngrok in `Procfile.dev` may be too opinionated but wanted to include it for a working example.
new script `bin/set-ngrok-url`
- Checks for running ngrok instance
- Outputs warning message if ngrok not running
- If ngrok is currently running, grab the current public URL
- If the current value of `BASE_URL` is different from the ngrok URL, update `BASE_URL` to current ngrok URL
- Output success message with URL (handy for command + click in the console to open)
- Whitelists ngrok URLs for hosts config
A script seemed the easier to evaluate if something like this would be useful.  I've also done something similar in a rake task to have the ability to check …

Add setup script to update BASE_URL with current ngrok url

---

test/system/dates_helper_test.rb
test/system/super_scaffolding_partial_test.rb

Continuation of #696.
Submitting as draft since I still have a little bit of work to do in the joint PR, https://github.com/bullet-train-co/bullet_train-core/pull/182

Update dates helper

---

test/system/account_test.rb
test/system/authentication_test.rb

These tests seem inconsistent, but that's due to the translation files in Devise, which are likely to change at some point.
The PR just changes the TODOs to note the reason for the inconsistency, and to (hopefully) offer some guidance for whoever discovers these tests failing in the future.
The Devise PR that will trigger a change at some point: https://github.com/heartcombo/devise/pull/5454

Make some TODOs more descriptive

---

bin/bump-core

Previously we were joining the rub gems names and passing that to `yarn upgrade`, which had no effect. Now we'll pass the actual npm packages that we want to update.

[release process] Fix the yarn update statement in bump-core

---

bin/bump-core

For some reason bundler isn't finding the new versions of the gems on rubygems. Weird.

[release process] Run `bundler outdated` to help debug

---

.github/workflows/publish-release.yml
.github/workflows/tag-release.yml

This should make it so that we automatically create a GitHub release after we auto-tag with a `v*` tag.

[release process] Trying to get auto tag & release working

---

.github/workflows/version-bump.yml

This makes it more clear that the PR is bumping the version on the `core` gems & packages.

[release process] Robustify the version-bump PR

---

test/factories/webhooks/incoming/stripe_installation_webhooks.rb
test/models/webhooks/incoming/stripe_webhook_test.rb
test/test_helper.rb

This PR implements some tests for https://github.com/bullet-train-pro/bullet_train-billing-stripe/pull/18. If the `bullet_train-billing-stripe` gem is not installed then these new tests will be skipped.
It also removes a (seemingly unused) factory that was duplicated out of `bullet_train-billing-stripe`.
This app still has access to that factory via the changes made to `test_helper.rb`.

Add tests for Stripe webhooks

---

.github/workflows/version-bump.yml

Installing `thor` in the workflow file because I'm not sure we want to include it as a dependency.

[release process] Install `thor` in release workflow

---

test/bin/setup-action-models-system-test
test/system/action_models_test.rb

This disable one thing related to actions models that were preventing that test from even starting, and then is disables a few invalid assertions that were causing failures after the test could actually start.
Joint PR: https://github.com/bullet-train-pro/bullet_train-action_models/pull/83

Fix action model tests

---

test/bin/setup-action-models-system-test
test/system/action_models_test.rb

This re-enables a test that was previously disabled, and it pulls in some test fixes from https://github.com/bullet-train-co/bullet_train/pull/730

Re-enable a test for Action Models

---

app/controllers/api/v1/memberships_controller.rb
app/views/api/v1/memberships/_membership.json.jbuilder
app/views/api/v1/open_api/index.yaml.erb
test/factories/memberships.rb

That implements memberships API, adds OpenAPI specs, and fixes path examples generation.
Required by https://github.com/bullet-train-co/bullet_train-core/pull/237

Memberships API

---

bin/bump-core

This will ensure that our `core` version bump PRs are limited to just `core` gems. The last couple have gotten some minor rails version bumps, but we should probably not include those. Dependabot will open PRs for that kind of thing.

[release process] Pass the `--conservative` flag to `bundle update`

---

Gemfile.lock

In https://github.com/bullet-train-co/bullet_train/pull/749 we tried to bump the version of `jbuilder-schema`, but since it's a dependency of `bullet_train-api` we need to leave it alone and let it get upgraded naturally when we bump that gem.

Fix an unintended change to `Gemfile.lock`

---

config/initializers/bullet_train.rb

Closes https://github.com/bullet-train-co/bullet_train-core/issues/454.
Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/461
We could technically put this in another file and write a block like this:
```ruby
BulletTrain::IncomingWebhooks::Configuration do |configure|
...
end
```
However, I think `BulletTrain::Configuration` is small enough right now so that we can put this all in one file.
I also used a String here and `constantize` it in the class itself to avoid constant loading issues on initialization.

Add configuration for incoming webhook parent class

---

test/controllers/api/open_api_controller_test.rb

In #749 we introduced more stringent checks in validating the Open API doc. https://github.com/bullet-train-co/bullet_train/pull/749/files#diff-c04c1d7b8b2c28801ca5fc5cfa976e08c1f9731284f8ad655655b2a12d9bcef6
After merging that, I also merged https://github.com/bullet-train-co/bullet_train-core/pull/257 and https://github.com/bullet-train-co/bullet_train/pull/737 which were both passing prior to merging.
I think that they probably would have failed that new test if their branches had been up to date. Since failing the tests if the doc is invalid is a brand new introduction, I'm going to disable those assertions in that test.

Disable a brand new test that's failing due to "merge conflicts"

---

bin/configure

Fixes #917.
There was some confusion surrounding #605 a while back and it was brought up a couple of times in Discord, so we should be telling developers to run `bin/setup` before they run `bin/dev`
Context:
- https://discord.com/channels/836637622432170028/836637623048601633/1131300251848945806
- https://discord.com/channels/836637622432170028/1116294694599663658/1116322544253947944

Ensure the setup script prompts developers to follow the correct setup steps

---

test/test_helper.rb

Fixes #657
Simplecov has to come before everything else in the test helper or it's unable to capture coverage information.

Make simplecov actually capture coverage data

---

config/initializers/backtrace_silencers.rb

Fixes https://github.com/bullet-train-co/bullet_train/issues/681
Before:
```
Error:
Account::TeamsControllerTest#test_should_get_edit:
ActionView::Template::Error: heck
test/controllers/account/teams_controller_test.rb:43:in `block in <class:TeamsControllerTest>'
```
After:
```
Error:
Account::TeamsControllerTest#test_should_get_edit:
ActionView::Template::Error: heck
/Users/jgreen/projects/bullet-train-co/bullet_train-core/bullet_train/app/models/concerns/users/base.rb:56:in `name'
bullet_train-themes-light (1.3.18) app/views/themes/light/menu/_user.html.erb:5
bullet_train-themes (1.3.18) app/helpers/theme_helper.rb:19:in `render'
bullet_train-themes-light (1.3.18) app/views/themes/light/menu/_account.html.erb:9
bullet_train-themes (1.3.18) app/helpers/theme_helper.rb:19:in `render' …
```

Show BulletTrain gems in stack traces by default

---

bin/configure

Closes #934.
This is a small detail, but there are two empty lines in place of this block now, and I decided to leave that much space instead of one line because there are some areas in this script where that extra space serves as a separator for meaningful chunks of code (and this part of the code is one of them).

Remove unneeded block from `bin/configure`

---

Gemfile
Gemfile.lock

This (mostly) fixes the problem reported in https://github.com/bullet-train-co/bullet_train-core/issues/464
However, due to https://github.com/bullet-train-co/bullet_train-core/issues/498 we don't currently try to show a user profile photo if we're using ActiveStorage instead of Cloudinary.
Here's some context about why we need to add this directly to the `Gemfile`.
https://github.com/libvips/ruby-vips/issues/155#issuecomment-1047370993

Add `ruby-vips` in the `:development` group

---

bin/bump-core

This is just a tiny typo fix; I could not unsee it.

Fix typo in bump-core banner

---

.circleci/config.yml

With parallelism set to 16 we spend about 75-80% of the time in any given job doing setup, and only 20-25% of the time running tests. Decreasing parallelism will give us a better ratio, and shouldn't increase testing time all that much.

Decrease parallelism in CircleCI

---

.circleci/config.yml
test/bin/setup-super-scaffolding-system-test

Solves the remaining problem in https://github.com/bullet-train-co/bullet_train-core/issues/453.
Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/543
We aren't running a system test, but by Super Scaffolding an incoming webhook and testing it this way, we can ensure that the scaffolder itself works.

Super Scaffold and test an incoming webhook

---

.circleci/config.yml

We don't actually use Firefox and we just waste time by installing it. It also seems to cause problems periodically as new versions are released. Removing it will allow us to sidestep those problems.

[CI] Install only Chrome and not Firefox in CircleCI

---

config/initializers/devise.rb

This helps in the "laptop left unlocked at a coffee shop" scenario.
If someone changes a user's email address, we'll send an email to the _original_ address to let them know.
Likewise if someone changes a user's password, we'll send an email to let them know.

Notify users when their email or password changes

---

test/system/resolver_system_test.rb

Closes #1008.
Works if:
1. No files have been ejected
2. If just the one file has been ejected with `bin/resolve shared/attributes/text --eject`
3. If a custom theme has been ejected i.e. - `rake bullet_train:themes:light:eject[foo]`

Fix resolver system test for ejected themes

---

test/mailers/previews/devise_mailer_preview.rb
test/mailers/previews/user_mailer_preview.rb

Fixes https://github.com/bullet-train-co/bullet_train-core/issues/266
Mailer previews can be found in `development` by going to:
<http://localhost:3000/rails/mailers/>

Implement mailer previews for built-in emails

---

test/application_system_test_case.rb

We were getting a green check when merging #1018, and I'm not sure if something changed along the way, but when signing out we get one of two notifications:
1. Signed out successfully.
2. You need to sign in or sign up before continuing
The latter happens when the root is the Team dashboard but the user isn't signed it so the user is redirected to the sign in page (This is our default setup).
The first happens when we use a custom, public page and the user is redirected to a page that doesn't need authentication.

Adjust `assert_text` for sign out method in application system test case

---

.circleci/config.yml
bin/updates/system_tests/use_device_test
test/application_system_test_case.rb

We're adding a new `device_test` helper that simplifies the structure of system tests.
In a following PR (#964) we'll update all of the system tests in the starter repo, but this might cause nasty merge conflicts for downstream developers. To reduce the chances of merge conflicts we're shipping a helper script that will make the expected changes to your system tests.
To use the helper to modify your tests run this in a console (after updating to v1.4.11):
```
bin/update/system_tests/use_device_test
```
Then you should:
* Run the tests to make sure they still pass
* Commit the updated test files
* Update to v1.5.0
We've introduced a new `device_test` helper that wraps up some of the implementation
details about running system tests on a variety of devices.
It simplifies the way that we …

[Action Required] Prevent merge conflicts for `device_test`

---

test/system/invitation_lists_test.rb
test/system/super_scaffolding_partial_test.rb
test/system/tangible_thing_test.rb

A few more instances of `assert page.has_content?` have crept in. Switching them to `assert_text` instead so that we get better error messages when tests fail.

Switch to assert_text in some more tests

---

.circleci/config.yml

In #720 we added a bit of setup to the CircleCI tests to run the `use_device_test` script in CI and then re-run the tests.
Now that we've merged that PR and the follow-on PR that changed the format of all the system tests, we no longer need to run that script and re-test in CI.

Remove testing for use_device_test transition script

---

test/concerns/fields/super_select_support_concern_test.rb

We added a new test in https://github.com/bullet-train-co/bullet_train/pull/1072 that we need to put behind the check for `HIDE_THINGS`.

Don't run scaffolding things related test if scaffolding things are hidden

---

test/system/webhooks_system_test.rb

Visit correct paths when developer menu is disabled in webhooks system test

---

bin/checkout-and-link-core-repo

For some reason all of a sudden GitHub doesn't like us sending a header.
Fixes https://github.com/bullet-train-co/bullet_train/issues/1089

[CI] Fix branch matching problem

---

test/system/animations_test.rb

We cleaned up most of these in
https://github.com/bullet-train-co/bullet_train/pull/720 but the conversion script couldn't see this one.
Fixes https://github.com/bullet-train-co/bullet_train/issues/1094

Replace a lingering instance of `resize_for`

---

test/system/action_models_test.rb

Joint PR
- https://github.com/bullet-train-pro/bullet_train-action_models/pull/90
As I mention in the comment, this error message is displayed for all actions, not just `targets-many`. I decided to place it here though because I don't think we need to go out of our way to create a parent model just to test this error message when we can test it against other models that are already in place.

Test Action Models error message for unneeded namespaces

---

bin/checkout-and-link-core-repo

When we do `bundle lock --update ...` that allows various dependencies to float up to a new version if one has been released. This prevents that from happening.
For instance in `bullet_train-api` we specify a dependency on `jbuilder-schema` of `>= 2.4.0`. In `Gemfile.lock` of the starter repo we had it set to `2.5.0`. But when `2.6.0` was released we started to see failured in CI due to a bug. Since the version was just "floating" to `2.6.0` in CI it wasn't immediately obvious that `jbuilder-schema` was getting updated.
Ideally we want to see these kinds of failures when Dependabot generates a PR to update our dependencies. In which case it would be much more obvious that a new verison of a gem is being used.

[CI] Prevent dependencies from floating when linking core repo

---

config/environments/development.rb
test/factories/invitations.rb
test/factories/memberships.rb
test/factories/scaffolding/completely_concrete/tangible_things.rb
test/factories/teams.rb
test/factories/users.rb
test/factories/webhooks/outgoing/endpoints.rb
test/factories/webhooks/outgoing/events.rb

Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/524
This PR adds some dummy ids to some of the `*_example` factories. (But not any "live" factories that are used outside of `ExampleBot`.)
Doing this so that the values can be pre-populated for `ExampleBot` without us needing to actually create live records, clone them, rollback, then reset primary keys. Doing all of that work is slow so it's best to avoid doing it. (And having to reset primary keys for something that we expect to be a normal thing kind of gives me the willies.)

Use `build` in ExampleBot instead of `create` + `rollback`

---

gitpod.Dockerfile

This should fix the Gitpod config.

Update Gitpod Dockerfile

---

test/system/invitation_lists_test.rb

A second attempt to close #1028.
Going with the sleep method because of the failure presented [here](https://github.com/bullet-train-co/bullet_train/issues/1028#issuecomment-1747344445)
FWIW, things are consistently passing locally for me. Maybe there's something on the CI environment that I'm missing.

Fix invitation lists test

---

.circleci/db_schema_check
.github/workflows/_database_schema_check.yml
.github/workflows/_deploy_heroku.yml
.github/workflows/_reusable_workflows.yml
.github/workflows/_run_super_scaffolding_tests.yml
.github/workflows/_run_tests.yml
.github/workflows/_standardrb.yml
.github/workflows/ci-cd-pipeline-bt-internal.yml
.github/workflows/ci-cd-pipeline-main.yml
.github/workflows/ci-cd-pipeline.yml
.github/workflows/tag-release.yml
.github/workflows/upgrade-bullet-train.yml
.github/workflows/version-bump.yml
bin/parallel-ci
postcss.mailer.config.js
test/system/super_scaffolding_test.rb

Fixes https://github.com/bullet-train-co/bullet_train/issues/764
Partially addresses https://github.com/bullet-train-co/bullet_train/issues/1010
This adds several new workflows for GitHub actions (and slightly tweaks some existing workflows to get them to display nicer with the new ones).
The `💻 PR CI/CD Pipeline (staging)` workflow is configured to automatically run whenever a PR is opened. It will run the main test suite, the super scaffolding tests, standardrb, and a database schema check. Tests are run in a matrix to speed things up, and the matrix can be configured in the workflow. The workflow can also be configured to auto-deploy to a staging app once the tests pass.
The `🎥 Main CI/CD Pipeline (prod)` is configured to automatically run whenever a commit lands on `main` either via a …

Add CI/CD workflows for GitHub Actions

---

Gemfile
Gemfile.lock

There's a bug in the latest version of `factory_bot_rails`: https://github.com/thoughtbot/factory_bot_rails/issues/433
There's also a fix that hasn't been merged or released yet: https://github.com/thoughtbot/factory_bot_rails/pull/432
I'm setting the `Gemfile` to specifically avoid those buggy versions so that we can get `depfu` un-blocked with keeping gems up to date.

Avoid buggy versions of factory_bot_rails

---

.circleci/config.yml
.github/workflows/_run_super_scaffolding_tests.yml
.github/workflows/_run_tests.yml
.github/workflows/ci-cd-pipeline-bt-internal.yml
.github/workflows/ci-cd-pipeline.yml

This makes it so that we run tests against the `core` repo as part of our internal pipeline.
(CircleCI is giving us trouble (again!), so it might be time to migrate away.)

[CI] Run CORE tests in GitHub Actions

---

test/concerns/fields/super_select_support_concern_test.rb
test/controllers/account/scaffolding/absolutely_abstract/creative_concepts_controller_test.rb
test/controllers/account/scaffolding/completely_concrete/tangible_things_controller_test.rb
test/controllers/api/v1/scaffolding/completely_concrete/tangible_things_controller_test.rb
test/system/account_test.rb
test/system/dates_helper_test.rb
test/system/fields_test.rb
test/system/pagination_test.rb
test/system/reactivity_system_test.rb
test/system/tangible_thing_test.rb
test/system/webhooks_system_test.rb

Fixes: https://github.com/bullet-train-co/bullet_train/issues/1174
Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/701
This PR makes it so that we don't have to run the test suite twice with both possible values of `HIDE_THINGS`. Instead of skipping tests if `HIDE_THINGS` is set to `true`, this makes it so that we set `HIDE_THINGS` to `false` before running those tests, and then we restore `HIDE_THINGS` to it's previous value.
The only functional potentially user-facing change is in the joint PR.

[CI] Handle HIDE_THINGS differently in tests

---

Gemfile
Gemfile.lock

It seems that `factory_bot_rails` unexpectedly introduced a breaking change. https://github.com/thoughtbot/factory_bot/issues/1602
For now I'm just going to avoid that version while we decide what to do about it: https://github.com/bullet-train-co/bullet_train-core/issues/707

Avoid more buggy FactoryBot versions

---

.github/workflows/version-bump.yml

In order to get the CI workflow to run after we create the upgrade PR we need to create the PR using a PAT. (Weird GitHub Actions rules... 🤷)

[Release process] Use a PAT to generate the upgrade PR

---

lib/tasks/auto_generate_diagram.rake

https://github.com/bullet-train-co/bullet_train/pull/1058
Reading up on https://github.com/voormedia/rails-erd/issues/322, `Zeitwork::Loader.eager_load_all` will ensure all of our application's models will be included when running `bundle exec erd`.
There were suggestions to put that line inside `config/environment.rb`, but I ultimately went with [this fix](https://github.com/voormedia/rails-erd/issues/322#issuecomment-517992445) which isolates it specifically to the scope of the `erd` command.
I'm not 100% happy having to include a file like this, but it seems like there [still isn't a fix for Rails 7](https://github.com/voormedia/rails-erd/issues/322#issuecomment-1153728972).
With that being said, the command is generating a PDF for the same amount of models (31) before and after this …

Eager load models when running `erd`

---

test/application_system_test_case.rb
test/system/fields_test.rb

See this issue on Capybara for additional details:
https://github.com/teamcapybara/capybara/pull/2726
This PR just registers a new version of `:selenium_chrome_headless`
instead of using the one registered in the `capybara` gem. The new one
just mirrors the fix that's already been applied to the gem, but not yet
released to rubygems.org. Once a new version of `capybara` is out, we
can remove the custom driver.

Fix for new versions of Chrome/webdriver

---

test/controllers/api/open_api_controller_test.rb

Makes OpenAPI test fail with explanation if Redocly couldn't parse openapi.yaml

Feature: Match failed parsing of api definition

---

.github/workflows/_database_schema_check.yml
.github/workflows/_run_super_scaffolding_tests.yml
.github/workflows/_run_tests.yml
.github/workflows/_standardrb.yml

Closes #1168.
I didn't add this to every environment, such as the PostgreSQL database setup in the following, but I can go ahead and add comments there too if necessary:
https://github.com/bullet-train-co/bullet_train/blob/8925e85a56f33df151df9623b120ef03a87d0994/.github/workflows/_database_schema_check.yml#L13-L20
@cc/ @olbrich

Add comment in GitHub Actions concerning `RAILS_MASTER_KEY`

---

test/application_system_test_case.rb

Fixes https://github.com/bullet-train-co/bullet_train/issues/1082
All this is because Rails' `test` method uses `define_method`, which will report this file as the `source_location`
and not the target test file where the test is actually defined.
`define_method` cannot be passed the correct location, we must use `class_eval` with a source string of Ruby for that.
But using a string means we can't refer to the block, like `define_method(name, &block)` would.
So we inject a module that we define methods via `test` to pass the block to, then we override that
via `class_eval` to point it to the correct location.

Redirect `device_test` definitions to correct test file.

---

bin/super-scaffold

Since `bin/super-scaffold` is still available in the current version of Bullet Train, this fix allows developers to run commands like `bin/super-scaffold action-models:targets-many Archive Project Team` against the new generators in the following PR:
- https://github.com/bullet-train-co/bullet_train-core/pull/736

Run Action Models generators with `bin/super-scaffold`

---

test/system/dates_helper_test.rb
test/system/tangible_thing_test.rb
test/system/teams_test.rb

Closes #1244.
Since we're using `User.find_by!` and it's not raising an error when the test fails, it seems to be an issue with the loading time for `visit`.
Granted, Capybara's max default wait time is `15` which seems to be set during `assert_text`, but it seems that `visit` hasn't finished loading before we get there so it gets applied to the onboarding step instead.
It might be due to the time it takes to look up the value in the database so I separated the logic here, but things are still passing for me locally so I plan on working on the branch here for a bit.
For what it's worth, this is the only file where we apply `find_by!` to link resolution in `visit` (one more for `Team` below), so I'm led to believe that's where the problem is.

De-flakify the TangibleThing system test (hopefully...)

---

.github/workflows/version-bump.yml

The `setup-ruby` action will use the version specified in the `.ruby-version` file.

Don't pin GitHub actions to a specific version of ruby

---

config/environments/production.rb

Fixes https://github.com/bullet-train-co/bullet_train/issues/1284
There may be better ways to handle this, but right now anyone who updates to a new version (or who starts a new project) is going to have trouble even booting their app in a production environment if they haven't configured S3.

Allow the app to boot if S3 is not configured

---

Gemfile
Gemfile.lock
app/views/layouts/_head.html.erb
config/environments/test.rb
test/application_system_test_case.rb

https://github.com/makandra/capybara-lockstep
Seems like it costs 5 seconds, but the build fails in strange ways. So I'm opening this for posterity.
I also used `bundle open bullet_train-themes-light` to add the expected JS include in `app/views/themes/light/layouts/_head.html.erb`:
```diff
+<%= capybara_lockstep if defined?(Capybara::Lockstep) %>
<%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
```
@gazayas @jagthedrummer I'll probably close this unless either of you feel like diving into the test failures, because I don't know what they mean 😊

Bundle capybara-lockstep to improve System Test stability.

---

app/assets/stylesheets/application.css
app/assets/stylesheets/application.custom.css
bin/theme
package.json
postcss.config.js
postcss.mailer.config.js

Resolves #567.
Replaces #1247.
Introduces a new local stylesheet:
`app/assets/stylesheets/application.css` loads `$ThemeStylesheet`, an alias that postcss-import resolves to the current theme's stylesheet, responsible for initializing tailwind. It also loads...
Both `postcss.config.js` and `postcss.mailer.config.js` are updated with a `postcssImportConfig`, which resolves the new `$ThemeStylesheet` alias. This allows us to continue not requiring to publish an npm package for each theme.
Joint PR:
* https://github.com/bullet-train-co/bullet_train-core/pull/741

Add default local stylesheet

---

test/system/fields_test.rb

`device_test` has undergone some changes, and although this was raising an error previously when running the entire test suite, no errors are being raised now.

Remove `device_test` fix for logged in users

---

test/application_system_test_case.rb

Closes #1084.
We don't have to add any assertions to the invitation tests themselves since we do that check here.

Account for invite-only mode in system tests

---

.github/workflows/_run_super_scaffolding_tests.yml

Follow-up to #1311
With the new directory we can ensure any new super scaffolding test file is automatically run, so we don't forget.

Run super scaffolding tests via directory

---

test/system/super_scaffolding/super_scaffolding_test.rb

Fixes #1315.
We were visiting the page here, but the actual `lint` command produces the documentation. You can verify this by simply running the tests, because the `puts` we have on the lint command outputs the results to the terminal.

Prevent scaffolding test from generating OpenAPI document unnecessarily

---

Gemfile.lock

For some reason `depfu` [is having trouble getting us up to date](https://github.com/bullet-train-co/bullet_train/pull/1313).
This is a fresh attempt to apply those updates to `main`.
```
bundle update bootsnap factory_bot
```

Update bundler dependencies

---

bin/configure

Closes #1330.
As the comment states, the command we use to retrieve system packages should return `redis` and/or `redis-server`:
```
> dpkg -l | grep '^ii' | grep redis
ii  redis                                      6:7.2.4-1rl1~focal1                        all          Persistent key-value database with network interface (metapackage)
ii  redis-server                               6:7.2.4-1rl1~focal1                        amd64        Persistent key-value database with network interface
ii  redis-tools                                6:7.2.4-1rl1~focal1                        amd64        Persistent key-value database with network interface (client)
```
I'm using Ubuntu 22.04 as well, so I'm not entirely sure why the problem in #1330 is happening.
```
> lsb_release -a
No LSB modules are …
```

Check for Redis in `bin/configure` via redis-cli

---

app/javascript/application.js
app/javascript/electron/index.js
app/javascript/support/jquery.js
package.json
yarn.lock

This is a re-do of https://github.com/bullet-train-co/bullet_train/pull/1319
Copied from that PR:
As a first step to completely remove jQuery as a dependency, we can at least remove the global `window.$` definition.
Joint PRs:
- https://github.com/bullet-train-co/bullet_train-core/pull/765
If your application still needs `$` defined globally, you can do the following:
1. `yarn add jquery`
2. Add the following lines to your `app/javascript/application.js` file:
```js
import jquery from "jquery";
window.jQuery = jquery;
window.$ = jquery;
```

Remove global `window.$` jQuery definition (redux)

---

bin/bump-core

Apparently we need to `yarn install` before we can upgrade, and now `yarn upgrade` has apparently be renamed to `yarn up`.

Fix the version bump action

---

test/test_helper.rb

Starting with verison `7.5.0` Knapsack Pro has begun to raise an error if it's missing the environment variables that tell it how to split tests. <https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/CHANGELOG.md#750>
That change has prevented `depfu` from being able to upgrade us to `7.5.0`. <https://github.com/bullet-train-co/bullet_train/pull/1493/checks?sha=563a3f0035beb0d929d33f2973a308d715222fec>
This makes it so that we don't automatically require Knapsack Pro if those env vars are missing.
(For "internal" purposes we don't use Knapsack at all, instead we use a crude splitting method to distribute tests across multiple runners on GitHub Actions. We also ship that same GHA workflow when people start a new repo.)

Prevent Knapsack Pro from failing if the KNAPSACK_PRO_CI_NODE_INDEX env var is missing

---

test/bin/setup-action-models-system-test
test/system/action_models_test.rb

This makes it so that the action models tests/setup uses the new `rails g super_scaffold:action_models:...` syntax instead of the old `bin/super-scaffold` syntax.

Use 'rails g super_scaffold:...' in action models tests

---

app.json

This PR does a few things to make the process of setting up an app on Heroku better and cheaper.
1. It adds a buildpack for `jemalloc` and sets the `JEMALLOC_ENABLED` ENV var. This helps with memory usage. Fixes: https://github.com/bullet-train-co/bullet_train/issues/1524
2. Makes the initial setup cheaper by using cheaper dynos and the entry level for a number of addons (in addition to removing the Bucketeer addon that seems questionably useful to begin with). This brings the monthly cost (as provisioned by `app.json`) down from ~$185/month to ~$22/month. Fixes: https://github.com/bullet-train-co/bullet_train/issues/1127
3. Removes the Sentry addon. This was redundant since Honeybadger was already included, and Sentry isn't supported in review apps on Heroku, so having it in `app.json` …

Better & cheaper initial experience on Heroku

---

.github/workflows/_run_super_scaffolding_tests.yml
test/bin/setup-super-scaffolding-system-test

Previously every node that ran _any_ super scaffolding test would also run the super scaffolding test for `PartialTest`.
This PR makes it so that we run that test on a dedicated node, and all the other nodes won't run it.
It also consolidates some super scaffolding tests onto the same CI node so that instead of running them across 9 nodes we run on 5.

Run the PartialTest on a dedicated CI node

---

config/database.yml

Some users are reporting crashes on MacOS when first trying to access the database. There's an issue open on `ruby-pg` that describes this temporary workaround. https://github.com/ged/ruby-pg/issues/538
Hopefully fixes: https://github.com/bullet-train-co/bullet_train/issues/1379

Fix for crashes on MacOS related to ruby-pg

---

app/views/active_storage/blobs/_blob.html.erb
app/views/layouts/action_text/contents/_content.html.erb
config/initializers/action_text_bug_fix.rb

Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/875
The two new files in `app/views` were generated by running `rails action_text:install`.
The `action_text:install` step also generated a few other files which we have in the `core` gems. So I haven't duplicated those here.
For instance it generates `app/assets/stylesheets/actiontext.css` but in the `core` repo we already have `bullet_train-themes-light/app/assets/stylesheets/light/actiontext.css`.
Things seem to work OK without these files, and I'm not _entirely_ sure that we really need them, but it seems like it would be a good idea to have them _somewhere_ since rails seems to expect them to be present. And since `rails action_text:install` will generate some duplicate files it seems like it might cause some …

Fix Trix Attachments

---

bin/configure-scripts/utils.rb

We were missing a `source` line which meant that the inline `Gemfile` couldn't install anything. So if you didn't already have the required gems installed it would fail.
Address the `colorizer` issue mentioned in https://github.com/bullet-train-co/bullet_train/issues/1606

Add a source to the inline Gemfile for `bin/configure`

---

Gemfile
Gemfile.lock

There are breaking changes in pagy versions 7 & 8 that we'll need to address. For now I'm pinning pagy to `< 7`. I've also done this in the `core` gems but I'm doing it here as well temporarily to be able to get some `depfu` updates in for the next version.

Pin pagy to verison 6

---

test/controllers/application/localization_test.rb

Fixes https://github.com/bullet-train-co/bullet_train/issues/1663
We shouldn't replace the whole Rails' app's RouteSet, particularly when the `@routes` instance variable already provides the hook.
Instead we can mirror what Rails does internally:
https://github.com/rails/rails/blob/a59ddc714fa0403cbd8c7ae6abdec2f71ee7b63f/actionpack/test/controller/test_case_test.rb#L1224C1-L1236C8

Fix flaky localization tests

---

test/system/super_scaffolding/partial_test.rb

Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/924

Change partial test to refer to 'files' not 'documents'

---

config/environments/development.rb

Because of https://github.com/bullet-train-co/bullet_train-core/issues/926

Disable raise_on_missing_callback_actions in development

---

app.json
bin/configure-scripts/deploy-buttons/heroku.md

The button needs to point at `www.heroku.com/deploy` not just `heroku.com/deploy` for it to even start to work.
Once you get past the first step it seems like having boolean literals in the `value` field causes problems (which are hard to debug because Heroku doesn't surface a useful error message).
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1609

Fix the "Deploy to Heroku" button

---

bin/configure-scripts/deploy_button_heroku.rb
bin/configure-scripts/deploy_button_render.rb
bin/configure-scripts/setup_github.rb

Closes #1607.
I figured we didn't want to entirely get rid of the `ask` methods here in case developers decide not to setup their project with GitHub. I tested the configure script against a personal repository of mine so it should work, but you can pull it down with this branch if you want to check it out:
```
> git clone -b refactor-github-details git@github.com:bullet-train-co/bullet_train.git bt_test
```

Calculate new repository link from ssh path in configure script

---

bin/configure-scripts/deploy-buttons/heroku.md

We used to provision higher production-ready tiers of the addons and when we updated `app.json` to provision demo-ready tiers we forgot to update the estimated cost of the addons.

Update the descirption of the "deploy to heroku" button

---

bin/configure-scripts/deploy_button_heroku.rb
bin/configure-scripts/deploy_button_render.rb

This makes it so that you can run either of these scripts independently of `bin/configure`:
* `./bin/configure-scripts/deploy_button_heroku.rb`
* `./bin/configure-scripts/deploy_button_render.rb`

Allow the deploy button scripts to be run in isolation

---

config/environments/development.rb
config/environments/production.rb
config/storage.yml

This makes it easier to use Cloudindary as the backend service for ActiveStorage. From a functional perspective this works very much like the S3 service option. ActiveStorage is still in control of files, but it sends them through to Cloudinary for storage and delivery.
**NOTE:** If, in production, you use Cloudinary for anything and have a `CLOUDINARY_URL` ENV var set but you want to use the `:local` option for ActiveStorage then you'll want to make an adjustment to `config/environments/production.rb`.
Partial fix for : https://github.com/bullet-train-co/bullet_train/issues/1617

Make it easier to use Cloudinary as a storage option for ActiveStorage

---

bin/setup-scripts/check_image_dependencies.rb

This makes it so that if you have either `vips` or `magick` available on your `PATH` that we count that as being good enough for image processing dependencies and we move on. Previously we'd check for both and prompt you to install both even though we only need one or the other. This should make it less confusing for people who don't realize that they're alternatives that do the same thing.

Refactor check_image_dependencies.rb to not require both vips and ImageMagick

---

Gemfile
Gemfile.lock
test/system/pagination_test.rb

This makes it so that we don't declare a direct dependency on `pagy`, but instead rely on the version specified by the `core` gems.
Joint PR in `core` that updates `pagy` from version 6 to version 8: https://github.com/bullet-train-co/bullet_train-core/pull/955
In `pagy` version 7 they [changed the default text](https://github.com/ddnexus/pagy/blob/master/CHANGELOG_LEGACY.md#visual-changes-possibly-breaking-testviews) for the "next page" and "previous page" buttons. For simplicity, and to reduce the amount of code that we need to support, we're sticking with the `pagy` defaults. Previously those buttons read `< Prev` and `Next >` and now they've dropped the text and just use the symbols `<` and `>`.
If you want to maintain the previous behavior you can [copy the pagy translation …

Upgrade pagy to version 8 (via `core`)

---

config/initializers/doorkeeper.rb
test/controllers/api/test.rb

The `password` and `implicit` grant flows are a little riskier from a security standpoint. We're removing them so that we ship a more secure default. It's easy enough for a developer add them to the Doorkeeper config if they're needed.
If you need to bring back one or both of these you can add them back to `config/initializers/doorkeeper.rb` here:
https://github.com/bullet-train-co/bullet_train/pull/1772/files#diff-c7fc4e057f18c41db72e3ab775f9871e6bee4d7e2b0aba1fdbfb2ea209dd2141L371-R371
Fixes https://github.com/bullet-train-co/bullet_train/issues/820

Remove a couple of the riskier Doorkeeper grant flows

---

app.json

We can use app.json to set an environment variable for apps deployed in Heroku. This is kind of the "first line of defense" for detecting that we're in Heroku. We'll also fallback to some other methods.
When the `BT_IS_IN_HEROKU` ENV var is set to `true` we'll assume that we're running in Heroku, and we'll sidestep any other detection methods.
We'll still fallback to our previous detection methods if that ENV var does not exist.
This also allows apps _not_ in Heroku to negate a false positive detection by our fallback methods by setting the `BT_IS_IN_HEROKU` ENV var to `false`.
Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/985

Improve Heroku Detection

---

bin/setup-scripts/check_postgres.rb
bin/setup-scripts/check_redis.rb

It's possible that a dev installs Postgres and Redis as prompted which will pass the installed check. However, if the dev has those services still turned off, they will fail later during the install, which can lead to confusion, frustration and less activations on BT.

Make turned off redis/pg non-breaking during setup

---

.github/workflows/ci-cd-pipeline-main.yml
.github/workflows/ci-cd-pipeline.yml

The official workflow for starndard rb requires that permissions be passed down through workflows. For some reason this is unneccessary in the starter repo itself, but for downstream apps GHA sometimes complains about standard rb missing required permissions. This should make it more stable across apps.
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1812

Fix for standardrb in GitHub Actions

---

package.json
yarn.lock

Before (notice the "Post-resolution validation" section):
```
$ yarn
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ app@workspace:. doesn't provide @hotwired/stimulus (pf1eaf), requested by stimulus-scroll-reveal.
➤ YN0002: │ app@workspace:. doesn't provide trix (pf188a), requested by @rails/actiontext.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 314ms
```
To generate this PR I did:
```
yarn add @hotwired/stimulus
yarn add trix
```
After
```
$ yarn
➤ …
```

Fix missing JS peer dependencies

---

bin/render-build.sh
render.yaml

Fixes https://github.com/bullet-train-co/bullet_train/issues/1638 (hopefully)
Reports from Render users suggest that `corepack enable` needs to be run both at build time and at run time. (If that's not the case someone please open another issue or PR with details.)

Run `corepack enable` on render

---

Gemfile
Gemfile.lock

This was an empty gem that didn't provide any real code.
Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/1031

Remove `bullet_train-scope_questions` gem

---

Gemfile
Gemfile.lock

`derailed_benchmarks` is useful for figuring out which gems require the most memory and for finding memory leaks.
See the derailed_benchmarks docs for details: https://github.com/zombocom/derailed_benchmarks

Add `derailed_benchmarks` to the `:development` group

---

Gemfile

We used to include `ruby-openai` as a dependency in the `.gemspec` of the main `bullet_train` gem. But we don't actually use it in any of the `core` gems or in the starter repo directly. The only place that we use it is in the `bullet_train-action_models` gem, and even there it's an optional dependency.
If you want to continue to use it you can uncomment the `ruby-openai` line in the `Gemfile`.
Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/1037

Add `ruby-openai` as an optional gem

---

Gemfile
test/test_helper.rb

We used to list `awesome_print` as a hard dependency in the main `bullet_train` gem. In an effort to reduce memory use in a new BT app we're now adding it as an optional dependency that developers can opt-in to using if they want to.
Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/1042

Add `awesome_print` as an optional gem

---

Gemfile

Previously we had `pry` in all groups, which meant that we were shipping it to production, but really you shouldn't need a debugger in production unless you really know what you're doing. Moving it to the `:development, :test` group makes it available in the places that you're most likely to need it while slimming down the production footprint.
If you need to use it in production for your app you can move it out of the `:development, :test` group in your `Gemfile`.

Move `pry` into the `:development, :test` gem group

---

Gemfile
Gemfile.lock
lib/tasks/aws.rake

We used to include several gems in the `:production` group of the `Gemfile` that may not be used in downstream apps. This PR comments them out in the `Gemfile` with the idea that people who need to use them can uncomment them to opt-in. This will make the default deployment image smaller than it was previously.
The new `:production` block of gems looks like this:
```ruby
group :production do
gem "terser"
end
```
You should evaluate whether you are using any of the gems that are commented out, and if so, you should un-comment them in your `Gemfile`.

Make a bunch of production gems optional

---

config/application.rb

For some reason we were explicitly requiring `pry` in `config/application.rb`. Doing so isn't necessary because it will automatically be required in the approriate environments because of it being in the `Gemfile`. This PR removes the uneccessary line.

Don't `require "pry"` in `config/application.rb`

---

Gemfile

The `core` gems used to list `xxhash` as a hard dependency, but it's only used in the generation of random colors for user & team icons.
If you have an existing app **and** you need to preserve the random colors that used to be generated you can uncomment this gem and things will continue to work the way they always have.
If you don't care about preserving the same random colors then you don't need to include it.
Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/1053

Add `xxhash` as an optional gem

---

Gemfile

This gem is used by one method in the `core` repo that we don't seem to use anywhere.
Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/1057

Add `unicode-emoji` as an optional dependency

---

Gemfile
Gemfile.lock

Previously we had listed `sidekiq` as a hard dependency of the `core` gems. This (and the joint PR) make it so that we list `sidekiq` directly in the `Gemfile` of the starter repo instead of as a gem dependency of the `core` gems. That will allow people to remove sidekiq if they want to use something else for background processing.
Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/1059

Hoist `sidekiq` into the `Gemfile` of the starter repo

---

app/avo/resources/team.rb
app/avo/resources/user.rb

Fixes #1371
This PR fixes the `time_zone` select field options on Avo resources.
Previously, the code:
```ruby
view_context.time_zone_options_for_select(Avo::Current.user.time_zone, nil, ActiveSupport::TimeZone)
```
was generating a `ActiveSupport::SafeBuffer`, which is not compatible with the select field `options` that expects a hash.

fix: avo `time_zone` options

---

Gemfile
Gemfile.lock

Previously we listed `rack-cors` as a hard dependency in the `core` gems, which meant that application developers were forced to include the gem even if they're not using the api. This makes it possible to remove `rack-cors` from the application completely.

Hoist `rack-cors` into the `Gemfile` of the starter repo

---

app/avo/resources/team.rb
app/avo/resources/user.rb

We accidentally got some trailing whitespace introduced that the linter doesn't like. This removes it.

Remove some whitespace

---

Gemfile
Gemfile.lock

Previously we listed `premailer-rails` as a hard dependency in the core gems, which meant that application developers were forced to include the gem even if they don't want to. This makes it possible to remove `premailer-rails` from the application completely.

Hoist `premailer-rails` into the `Gemfile` in the starter repo

---

Gemfile

We were pointing to the wrong gem documentation page (openai-ruby vs ruby-openai). Took me a minute to realize it wasn't correct.

Fix openai documentation url

---

Gemfile.lock

After pulling down the latest starter repo and running `bundle install` this line was automatically added to `Gemfile.lock`. I think this has to do with the latest updates to MacOS.

Add `arm64-darwin-24` to `Gemfile.lock`

---

app/javascript/controllers/index.js

Updates the way `controllers/index.js` loads local controllers, allowing them to take precedence over controllers of the same name from Bullet Train's packages.
To reproduce:
* Create a new project using this branch
* Create a local `controllers/fields/super_select_controller.js` empty file
* Add the following to that new file, which will inject a `console.log` in the `connect()`
```js
import { SuperSelectController } from '@bullet-train/fields'
export default class extends SuperSelectController {
connect() {
console.log('super_select_controller connected')
super.connect()
}
}
```

Allow local overrides of Bullet Train's Stimulus controllers

---

app/views/layouts/_head.html.erb

With new tag `mobile-web-app-capable`
Example https://github.com/vercel/next.js/issues/70272

Replace deprecated tag `apple-mobile-web-app-capable` with `mobile-web-app-capable`

---

lib/tasks/stimulus_manifest_update_override.rake

Fixes https://github.com/bullet-train-co/bullet_train/issues/2011
With this task override active you'll see this when generating a new stimulus controller:
```
$ rails g stimulus MyNewController
create  app/javascript/controllers/my_new_controller.js
rails  stimulus:manifest:update
-----------------------------------------------------------------------------------
We are skipping the stimulus:manifest:update task to avoid clobbering our manifest.
If you need to run this task pass it the `--clobber` option like this:
bin/rails stimulus:manifest:update -- --clobber
-----------------------------------------------------------------------------------
```
If you do `bin/rails stimulus:manifest:update -- --clobber` then we avoid overriding the task, and we run the original task, which will …

Avoid clobbering our Stimulus manifest file when generating a new controller

---

.github/workflows/_run_super_scaffolding_tests.yml
.github/workflows/_run_tests.yml
Gemfile.lock
app/javascript/application.js
package.json
test/application_system_test_case.rb
test/system/invitations_test.rb
test/system/super_scaffolding/project/project_test.rb
yarn.lock

Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/1134
**NOTE** The failing tests here are expected. They're the ones that are testing against the currently published gems. Those gems depend on `rails-ujs` so they fail when it's not there. All of the tests against `core` are passing because it's running on the `jeremy/turbo-delete` branch which uses turbo instead of rails-ujs.

Remove rails-ujs

---

config/initializers/pagy.rb
test/system/pagination_test.rb

Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/1150
The test failures here are in the part of the test suite that's testing against the published gems, which expect `pagy` version 8, so they're to be expected.

Updates for `pagy` 9

---

.github/workflows/_run_super_scaffolding_tests.yml

This prevents possible collisions

For superscaffolding tests name artifacts differently

---

.github/workflows/docker.yml

It's impossible to run a workflow until it exists in the `main` branch.
So this is just a PR to add a workflow that probably doesn't work so that it can be run in a different branch in order to debug and get it working.

Add an exploratory GitHub workflow for building Docker images

---

bin/dev

Depending on your local configuration you may _need_ `bundle exec` to be included in these commands. In either case adding it won't hurt anything.

Use `bundle exec` in `bin/dev`

---

bin/configure-scripts/deploy_button_heroku.rb

Reproduction:
The user runs `bin/configure` and responds `n` to "Continue setting up with Github". (NB: this sets the global `SETUP_GITHUB` to `false`)
The user later responds 'y' to "Would you like to add a 'Deploy to Heroku' button to your project. [Y/n]". This results in the following error:
```text
Adding a 'Deploy to Heroku' button.
/path_to_project/bin/configure-scripts/deploy_button_heroku.rb:13:in '<top (required)>': uninitialized constant HTTP_PATH (NameError)
HTTP_PATH
^^^^^^^^^
from /Users/grymoire/rbenv/versions/3.4.5/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
from /Users/grymoire/.rbenv/versions/3.4.5/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
from bin/configure:22:in '<main>'
```
The line of code in question is …

fix small SETUP_GITHUB issue

---

package.json
yarn.lock

The new sortable controller in `core` doesn't need it anymore. And we probably shouldn't have had it as a dependency in the app to begin with.
Joint PR: https://github.com/bullet-train-co/bullet_train-core/pull/1222

Remove `dragula` as an application dependency
